### ISSUE TITLE
목록을 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 'remove_duplicates'라는 함수를 작성하세요.

### ISSUE THREAD

**Issue by sonsj1824** [encore-playdata/blogging#10]
목록을 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 'remove_duplicates'라는 함수를 작성하세요.

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 리스트를 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 함수입니다.

def remove_duplicates(list):
    result = []
    for item in list:
        if item not in result:
            result.append(item)

    return result
    
# 테스트 코드
list = [1,2,3,4,5,1,2]
print(remove_duplicates(list)) # [1, 2, 3, 4, 5]

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 리스트를 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환합니다. 
코드 예시:
def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)
    return new_list

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 목록을 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 함수입니다.

def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)

    return new_list

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 리스트를 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 함수입니다.

def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)
    return new_list

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 리스트를 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 함수입니다.

def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)

    return new_list

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 리스트를 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환합니다.

def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)
    return new_list

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 목록을 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 함수입니다.

코드 예시:
def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)

    return new_list

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 목록을 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 함수입니다.

코드 예시:
def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)

    return new_list

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 목록을 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 함수입니다. 즉, 인수로 받은 목록에서 중복 항목이 제거된 결과 목록을 반환합니다.

코드 예시:
def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)

    return new_list

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 목록을 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 함수입니다.

def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)
    return new_list

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 리스트를 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 함수입니다. 

def remove_duplicates(mylist):
    newlist = []
    for item in mylist:
        if item not in newlist:
            newlist.append(item)

    return newlist

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 목록을 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환하는 함수입니다.

def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)

    return new_list

**Comment by encore-playdata** [comment]
remove_duplicates 함수는 리스트를 인수로 받아 모든 중복 항목이 제거된 새 목록을 반환합니다. 
코드 예시:
def remove_duplicates(list):
    new_list = []
    for item in list:
        if item not in new_list:
            new_list.append(item)
    return new_list
