### ISSUE TITLE
질문 test

### ISSUE THREAD

**Issue by sonsj1824** [encore-playdata/blogging#11]
문자열을 인수로 받아 True를 반환하는 'is_palindrome'이라는 함수를 작성하세요. 문자열이 회문이면 False이고 그렇지 않으면 False입니다.

**Comment by encore-playdata** [comment]
회문이란 앞에서부터 읽어도 뒤에서부터 읽어도 같은 단어, 문구 또는 숫자의 순서를 말합니다.

'is_palindrome' 함수는 문자열을 인수로 받고, 해당 문자가 회문일 경우 True, 그렇지 않을 경우 False를 반환합니다.

def is_palindrome(string):
    if string == string[::-1]: # [::-1] : reverse the string
        return True
    else:
        return False

**Comment by encore-playdata** [comment]
회문이란 앞에서부터 읽으나 뒤에서부터 읽으나 같은 단어, 구, 문장을 말합니다. 
'is_palindrome'이라는 함수는 문자열을 인수로 받고, 그 문자가 회문이면 True, 그렇지 않다면 False를 반환합니다.

def is_palindrome(string):
    if string == string[::-1]: # [::-1] : reverse slicing
        return True
    else:
        return False

**Comment by encore-playdata** [comment]
회문이란 앞에서부터 읽어도 뒤에서부터 읽어도 같은 단어, 문구, 구절 등을 말합니다.

'is_palindrome' 함수는 문자열을 인수로 받고, 해당 문자가 회문일 경우 True, 회문이 아닐 경우 False를 반환합니다.

def is_palindrome(string):
    if string == string[::-1]: # [::-1]은 리스트의 원소를 -1(=reverse)한다는 의미
        return True
    else:
        return False

**Comment by encore-playdata** [comment]
is_palindrome 함수는 문자열을 인수로 받아 회문인지 아닌지 확인합니다. 문자열이 회문이면 True, 그렇지 않으면 False를 반환합니다.

def is_palindrome(string):
    return string == string[::-1]
