### ISSUE TITLE
문자열을 인수로 받아 문자열의 모음 수를 반환하는 'count_vowels'라는 함수를 작성하세요. .

### ISSUE THREAD

**Issue by sonsj1824** [encore-playdata/blogging#9]
문자열을 인수로 받아 문자열의 모음 수를 반환하는 'count_vowels'라는 함수를 작성하세요. .

**Comment by encore-playdata** [comment]
문자열을 인수로 받아 문자열 내의 모음(a, e, i, o, u) 수를 반환하는 함수 'count_vowels'를 작성합니다.

def count_vowels(string):
    vowels = "aeiou"
    return sum([1 for char in string if char in vowels])
    
print(count_vowels("apple")) # 2

**Comment by encore-playdata** [comment]
문자열을 인수로 받아 문자열의 모음 수를 반환하는 'count_vowels' 함수는 다음과 같이 구현할 수 있습니다.

def count_vowels(string):
    vowels = "aeiou"
    count = 0

    for char in string:
        if char in vowels:
            count += 1

    return count

**Comment by encore-playdata** [comment]
count_vowels 함수는 문자열을 인수로 받아 문자열의 모음 수를 반환합니다. 

def count_vowels(string):
    vowels = 'aeiou'
    count = 0

    for char in string:
        if char in vowels:
            count += 1

    return count

**Comment by encore-playdata** [comment]
문자열을 인수로 받아 문자열의 모음 수를 반환하는 'count_vowels' 함수는 다음과 같이 구현할 수 있습니다.

def count_vowels(string):
    vowels = "aeiou"
    counter = 0

    for char in string:
        if char in vowels:
            counter += 1

    return counter

**Comment by encore-playdata** [comment]
count_vowels 함수는 문자열을 인수로 받아 문자열의 모음 수를 반환합니다.

def count_vowels(string):
    vowels = 'aeiou'
    count = 0

    for char in string:
        if char in vowels:
            count += 1

    return count

**Comment by encore-playdata** [comment]
count_vowels 함수는 문자열을 인수로 받아 문자열의 모음 수를 반환합니다.

def count_vowels(string):
    vowels = "aeiou"
    counter = 0

    for char in string:
        if char in vowels:
            counter += 1

    return counter

**Comment by encore-playdata** [comment]
count_vowels 함수는 문자열을 인수로 받아 문자열의 모음 수를 반환합니다.

def count_vowels(string):
    vowels = "aeiou"
    num_vowels = 0

    for char in string:
        if char in vowels:
            num_vowels += 1

    return num_vowels

**Comment by encore-playdata** [comment]
count_vowels는 문자열을 인수로 받아 문자열의 모음 수를 반환하는 함수입니다. 이 함수는 문자열을 전달받고, 그 문자열 안의 'a', 'e', 'i', 'o', 'u'가 몇 개가 있는 지 확인합니다. 그리고 확인한 결과를 다시 반환합니다.

def count_vowels(string):
    vowels = "aeiou"
    count = 0

    for char in string:
        if char in vowels:
            count += 1

    return count

**Comment by encore-playdata** [comment]
count_vowels 함수는 문자열을 인수로 받아 문자열의 모음 수를 반환합니다. 

def count_vowels(string):
    vowels = 'aeiou'
    count = 0

    for char in string:
        if char in vowels:
            count += 1

    return count

**Comment by encore-playdata** [comment]
문자열을 인수로 받아 문자열 내의 모음 수를 반환하는 함수 'count_vowels'는 아래와 같이 구현할 수 있다.

def count_vowels(string):
    vowels = "aeiou"
    return sum(1 for char in string if char in vowels)
    
# 테스트
print(count_vowels("apple")) # 2

**Comment by encore-playdata** [comment]
문자열을 인수로 받아 문자열 내의 모음 수를 반환하는 함수 'count_vowels'는 아래와 같이 구현할 수 있다.

def count_vowels(string):
    vowels = "aeiou" # 모음
    count = 0 # 모음 개수

    for char in string: # string을 한 글자씩 탐색
        if char in vowels: # char가 vowels 내의 문자라면
            count += 1 # count 1 증가

    return count # count 값 반환

**Comment by encore-playdata** [comment]
count_vowels 함수는 문자열을 인수로 받아 문자열의 모음 수를 반환합니다. 
각각의 문자가 a, e, i, o, u 중 하나인 경우 1을 더해 카운트합니다.

def count_vowels(string):
    vowels = "aeiou"
    count = 0

    for char in string:
        if char in vowels:
            count += 1

    return count
